artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_url: https://github.com/Soura10/test-1/blob/main/WineQT.csv
   local_data_file: artifacts/data_ingestion/data.csv
   #unzip_dir: artifacts/data_ingestion
